name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        id: code
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Package Manager
        run: npm install -g pnpm
        id: globalInstall
      - name: Install Dependencies
        run: pnpm install
        id: deployInstall
      - name: Build
        run: pnpm run build
      - name: Setup Environment
        run: echo ${{ secrets.TEST_DOTENV }} > .env.test.local
      - name: Test
        run: pnpm run test:ci
